### ISSUE TITLE
Unable to create file lint-and-test.yml: 'matrix' is undefined

### ISSUE THREAD

**Issue by Flix6x** [FlexMeasures/flexmeasures-plugin-template#10]
Running `cookiecutter https://github.com/SeitaBV/flexmeasures-plugin-template`, I got this message after filling out the required info:

```
Unable to create file '.github/workflows/lint-and-test.yml'
Error message: 'matrix' is undefined
```

I noticed this 'matrix' part has been commented out in the `lint-and-test.yml` of [another plugin](https://github.com/SeitaBV/flexmeasures-zinfo/blob/main/.github/workflows/lint-and-test.yml)?

**Comment by nhoening** [comment]
Haven't worked with this in a while, but it seems that this is a clash between cookiecutter and GithubAction Yaml variable escaping. 

[We're using this exact syntax in FlexMeasures right now](https://github.com/FlexMeasures/flexmeasures/blob/main/.github/workflows/lint-and-test.yml#L26), but we should make sure cookiecutter doesn't try to fill it in.

CookeiCutter uses Jinja, so [this](https://jinja.palletsprojects.com/en/3.1.x/templates/#escaping) might be what we should try.

**Comment by nhoening** [comment]
Resolved in https://github.com/FlexMeasures/flexmeasures-plugin-template/commit/e38f1b9316c55153456d9ff4e87826fded353922
